runtime: nodejs20

instance_class: F4

entrypoint: node server.js

env_variables:
  NODE_ENV: "production"
  AWS_LAMBDA_FUNCTION_NAME: true

automatic_scaling:
  min_instances: 1
  max_instances: 2

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
