runtime: nodejs20

instance_class: F4

entrypoint: node server.js

env_variables:
  NODE_ENV: "production"
  AWS_LAMBDA_FUNCTION_NAME: true

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 30s
  max_pending_latency: 60s


resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
