runtime: nodejs20

instance_class: F1  # أقل فئة (الأقل تكلفة)

entrypoint: node server.js

env_variables:
  NODE_ENV: "production"
  AWS_LAMBDA_FUNCTION_NAME: true

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 0
  min_pending_latency: 0.1s
  max_pending_latency: 1.0s

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
